### ISSUE TITLE
Send messages only from logged users

### ISSUE THREAD

**Issue by davmann** [michael-milette/moodle-local_contact#16]
Hi, I like this plugin. Simple and easy. :-)
I have only one problem. In my side, it seems only logged users can send messages.
I tried also with Guest user, I can see the static page with the form, but I cannot submit. After click on "send", I have a blank page with the word "Forbidden".
If log in, all is perfect.
Do I have to change something in my config somewhere?
Thanks

**Comment by michael-milette** [comment]
Hi Davmann,

Are you using the version from Moodle.org or the one here on GitHub? The GitHub version is currently slightly newer than the Moodle.org version.

There are certain elements of a form that must be included in order for the form to work. Given that it is working for you with logged-in users, I am guessing that you downloaded the plugin.

The "name" and "email" address fields are not required for logged in users. In fact, they will be ignored if present. However, for users who are logged out, these two fields are mandatory. If they are missing, you will see the "Forbidden" page.

If that doesn't help, turn on the Moodle developer debugging mode to see more information on the nature of the problem.

If you still can't figure out the problem, post the form's HTML code or post a link to your page and I will take a quick look at it.

**Comment by davmann** [comment]
Hi Michael,
fixed https with htaccess and in moodle config (for logins).
Now, all is working!

The problem was probably with firefox. I use that browser for test in logout mode. 
It was not able to autoswich (like chrome) from http to https. So probably, after getting the https page, it submitted the form in http. Probably that was the problem, but cannot be sure.


Anyway, just in case someone will fall in the same trouble, here are the lines I added to the default moodle .htaccess
```
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,L]
```

So, Problem solved.
Thanks!

**Comment by michael-milette** [comment]
Hi davmann,

Glad to hear that you solved your issue. Another solution might be to use protocol-relative (a.k.a. schemeless) URLs. The action in your form would point to something like:

    action="//example.edu/local/contact/"

There are some drawbacks to using these types of URL's such as support for older web browser (<=IE8). Some people have also reported issues when these types of URLs are involved in redirects.

However, if that isn't a problem for your situation (probably isn't), this solution would enable your form to work for both http and https.

Best regards,

Michael

**Comment by michael-milette** [comment]
Here is an alternative for your .htaccess which will not only automatically switch you to HTTPS but also add www. to the domain:

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{SERVER_PORT} 80 
  RewriteCond %{HTTP_HOST} ^example.com [NC,OR]
  RewriteCond %{HTTP_HOST} ^www.example.com [NC]
  RewriteRule ^(.*)$ https://www.example.com/$1 [L,R=301,NC]
</IfModule>

There are really so many ways to do this.

**Comment by michael-milette** [comment]
By the way, the FilterCodes plugin is now available on [moodle.org/plugins/filter-filtercodes](https://moodle.org/plugins/filter-filtercodes)

It includes a tag called {wwwroot}. Just use that in the form's action with /local/contact and it will always point to the correct protocol, domain and path of the plugin.
