### ISSUE TITLE
How Can I make ReCaptcha to be mandatory?

### ISSUE THREAD

**Issue by kostaslm** [michael-milette/moodle-local_contact#24]
I have configured Contact Form and I can see recaptcha in my form. But when I send a test submition recaptcha is not mandatory. What I have to do?

**Comment by michael-milette** [comment]
Hi @kostaslm ,

Thank you for taking the time to contribute your question. I really appreciate it.

Unfortunately the recaptcha feature isn't finished yet, much less actually tested. As you noticed, the plugin isn't aware of recaptcha when it receives the form. Unfortunately recaptcha has not yet been implemented however I am hoping to find the time to include it in the next release of Contact Form due out around November / December (usually just before each major release of Moodle itself). If you are in a hurry for this feature to be implemented and would like to get it sooner, I am available for hire. :-)

With that said, have you tried it without recaptcha? There are other anti-spam features built into Contact Form for Moodle which should prevent spam emails.

Let me know if you can wait for the next release (I will notify you) or if you would like it sooner.

Best regards,

    Michael

**Comment by michael-milette** [comment]
Hi @kostaslm,

Thank you for your patience. Great news! ReCAPTCHA is now officially supported as of the latest versions of both Contact Form for Moodle and FilterCodes for Moodle. You will need to update both of them in order for it to work.

Note that ReCAPTCHA will not appear or be required if the user is logged in as a non-guest user.

The updated version of the plugin will be posted on Moodle.org on November 11, 2017.

Best regards,

Michael Milette
