### ISSUE TITLE
Add Setting to Require Login

### ISSUE THREAD

**Issue by jezhops** [michael-milette/moodle-local_contact#37]
We are in the proces of adding the following feature and will submit a pull request shortly:

For use the fact non authenticated users can post requests to this plugin is an issue. We only want to use it internally and do not want the form accessible to non authenticated users, this is to be sure it cannot be abused.

1) Add a checkbox setting to the admin pages "strict_users" 
2) If enabled the login form will not process any emails from guest users instead re-directing them to the login page
3) This setting will be enabled by default, but that could easily be altered to being disabled by default

Although our HTML forms all require login this would prevent anyone who knew the URL of the local plugin from creating their own POST form and submitting from outside of Moodle when not logged in.

**Comment by michael-milette** [comment]
Hi @jezhops ,

Thank you very much for your feedback and for offering to contribute through a pull request. I really appreciate your time and effort.

You may find it to be somewhat more challenging than you think to reproduce your scenario. There are already several anti-SPAM measures currently in place to prevent someone from submitting their own POST form from outside of Moodle - regardless of whether they are logged into Moodle or not.

With that said, I think this suggestion may merit some consideration, if for nothing else but to automatically take them to the login page. Then again, if someone is trying to hack your webmail form  system, do you really want to be kind and take them to the front door? Currently the system will just take them to a blank page leaving them clueless about why it didn't work - unless debugging is enabled.

Have you actually succeeded in reproducing your scenario? Please let me know. Also, when preparing your pull request, please be sure to follow the guidelines in [CONTRIBUTING.md](https://github.com/michael-milette/moodle-local_contact/blob/master/CONTRIBUTING.md).

Looking forward to hearing back from you. Thanks again for contributing!

Best regards,

Michael

**Comment by kmoouni** [comment]
Hi Michael,
Yes easily able to produce the scenario, not too tricky. 
Perhaps best to PM the steps rather than report here?

I can see the argument for not redirecting to the front door, but a miscreant already knows your moodle server - that's why they are using the scenario.
Kevin

**Comment by michael-milette** [comment]
Hi @kmoouni ,

Please do PM me the steps. If you are POSTing the message from some other server, there might be a bug in my anti-spam strategy which should be fixed.

You can PM me through Moodle.org or by sending me a message through my website at https://www.tngconsulting.ca/contact. Messages come straight to me.

Best regards,

Michael

**Comment by jezhops** [comment]
Hi Michael,

If we wanted to spam this form I believe we could:

1) Create an HTML form on our pc to post to the local plugin
2) Spoof the HTTP referer to get around the existing check

https://en.wikipedia.org/wiki/Referer_spoofing

There are plugins for Firefox and Chrome that make spoofing the referer trivial:

https://chrome.google.com/webstore/detail/referer-control/

_

> "Referer Control grants full control over the HTTP Referer. You can forge any referrer you want, both globally or on a per-site basis. Alternatively you can choose to disable the Referer completely.
> 
> Also works on the JavaScript document.referrer!"

_

**Comment by michael-milette** [comment]
Hi @jezhops ,

@kmoouni provided an example on how he would hack a form submission. While his approach would work, this hack can still be blocked making use of ReCAPTCHA. Simply configure the keys in Moodle. You won't even need to add the recaptcha in your form. Here's why.

Contact Form for Moodle always ignores ReCAPTCHA for logged-in users but requires it if the keys are configured and the user is logged-in (there is an override option available in the settings).

The end result is that logged-out users will not be able to submit an webmail message and logged-in users will not be impacted at all. This feature is only available as of Contact Form version 0.8.

All that said, I will still look forward to receiving your pull request if you would rather see it included.

Best regards,

Michael

**Comment by jezhops** [comment]
Hi Michael,

That sounds a bit complicated to be honest, I think the other issue is what we do with those are not authenticated.

I think Kevins approach of redirecting to the login page is not the best approach as useres would not necessarily realise their email had not been sent, if for example their Moodle session had expired.

I think a better approach would be to print a message on the screen saying something to the effect of "You must be logged in to send messages through this form"

We will make that change before submitting the pull request.

**Comment by michael-milette** [comment]
This issue has been addressed in #41. Not exactly implemented the way your code did but it should meet your needs for now.

What this change does is to assume the user is legitimate and that their session has simply timed-out if they are logged out. This should also handle the situation where someone is trying to hack a form submission.

At some point in the future, I may spend additional time considering how this could be accomplished while preserving data submitted from the form.
