### ISSUE TITLE
SessKey not required

### ISSUE THREAD

**Issue by jezhops** [michael-milette/moodle-local_contact#39]
Whist testing we noticed it was possible to send emails with no sesskey defined in the submit form.

I am not sure if there has been a change not reflected in the documentation or wehther this is a bug.

We were testing as a logged in user.

**Comment by michael-milette** [comment]
Thank you for bringing this to my attention. The sesskey should definitely be a requirement. I will get back to you on this.

**Comment by jezhops** [comment]
Ok, I would add that we are using the version with the new field and that was set to "require login", not sure if that would have an impact, I dont think so.

**Comment by michael-milette** [comment]
No, it doesn't have any impact. I found the problem. It was incorrect parenthesis evaluation on line 126 of class/local_contact.php. I will be pushing the update shortly, as soon as I finish my testing.

Thanks for bringing this to my attention.

Best regards,

Michael

**Comment by michael-milette** [comment]
Fixed in #41 . This fixes the sesskey issue.
