### ISSUE TITLE
Feature Request: Option to remove site name from subject

### ISSUE THREAD

**Issue by jezhops** [michael-milette/moodle-local_contact#42]
Currently there doesnt seem to be a way to remove [Moodle Site Name] from the subject of the email sent. This is prefixed on the server side.

It would be useful to have another option to be able to disable this feature:

> Setting Name: prefix_subject_with_site_name
> Default Value: true (consistent with current version)

When disabled the site name would be removed.

The reason we would like this so that subject lines become clearer / more distinct for our helpdesk and are routed to the correct team. We will be creating several request forms for different purposes.

If you are agreeable to this feature being added we can do this and submit a pull request.

**Comment by michael-milette** [comment]
Thank you for contributing this suggestion. The feature you requested has been added to the DEV branch of the plugin and will be included in the next release of Contact Form for Moodle scheduled to come out in April/May 2018.

If you have a chance, please feel free to test the new feature and re-open this issue if it doesn't work as expected.

Best regards,

Michael
