### ISSUE TITLE
"Forbidden" error

### ISSUE THREAD

**Issue by wallyreport** [michael-milette/moodle-local_contact#58]
Moodle 3.7.7. Boost theme. Using LetsEncrypt. No SSL or TLS set on SMTP server. I am not using Apache mod_rewrite.

Cannot seem to get past this error. I am pretty sure the /local/contact/index.php file is being found. I have tried changing permissions to 755. I think this has something to do with the sesskey. I used to get a sesskey error, now I just get one word "forbidden."   

Users can self register on my Moodle site, so I know the email is working.

**Comment by michael-milette** [comment]
Hi @wallyreport ,

I just updated the plugin to be compatible with Moodle 3.9. Although I doubt that there are any changes that will fix your issue, I did add a new question in the FAQ that may help you. Take a look at:

https://github.com/michael-milette/moodle-local_contact#why-isnt-my-form-working

The Forbidden error is usually related to missing fields in the form which can include the javascript snippet for sesskey.

If this doesn't help, please send me a link to your form if you can. If you would rather not publish the link here, you can send me a private message through my website at https://www.tngconsulting.ca/contact

Best regards,

Michael

**Comment by michael-milette** [comment]
As I have not heard back from you in over a month, I will assume that you resolve the issue and am therefore closing this ticket.
