### ISSUE TITLE
Improve validation of HTTP_USER_AGENT and HTTP_REFERER values

### ISSUE THREAD

**Issue by tmuras** [michael-milette/moodle-local_contact#59]
$_SERVER['HTTP_USER_AGENT'] and $_SERVER['HTTP_REFERER'] are used to create part of the HTML message - https://github.com/michael-milette/moodle-local_contact/blob/master/classes/local_contact.php#L320 . 
It would be a good idea to sanitize / validate those values as they are untrusted - passed from user's browser.

**Comment by michael-milette** [comment]
Hi @tmuras , thank you for your feedback. 

As the tool is only available to your Moodle Administrators, do you not trust them?

Just kidding. As requested, the $_SERVER['HTTP_USER_AGENT'] and $_SERVER['HTTP_REFERER'] are now sanitized. The fix will be included in the next release of Contact form for Moodle which should be released over the next couple of days.

Again, thanks for your suggestion!

Best regards,

Michael
