### ISSUE TITLE
reCAPTCHA alternatives

### ISSUE THREAD

**Issue by zeigerpuppy** [michael-milette/moodle-local_contact#60]
For some users, it is not possible or desirable to use Google reCAPTCHA. Examples of such users include:
- users from locations which can't access reCAPTCHA (especially China)
- users concerned about leaking IP and profile data to Google
- users who object to training neural networks for a private company
- sites that are handling sensitive data with high level privacy needs (i.e. no 3rd party data processors).

It would be great to have alternative(s) to reCAPTCHA for the local_contact form.  This could be:
1) a simple honeypot for spambots (a hidden submission field that a spam bot enters but a user does not).  The technique is described [here](https://stackoverflow.com/questions/28101429/receiving-spam-from-my-form-using-phpmailer) and I can attest to it being very effective.
2) adding a simple problem for the contact sender to solve (an addition or division problem for instance)
3) using an alternative open source (and self-hosted) CAPTCHA alternative like https://github.com/desirepath41/visualCaptcha

While none of these will defeat a directed attack, they are often very effective against simple bots.

**Comment by michael-milette** [comment]
Hi @zeigerpuppy , I agree. That is why Contact Form has a setting to turn reCAPTCHA off, even if it is turned on in Moodle.

Since many years, Contact Form implements several invisible techniques to minimize spam without reCAPTCHA. Feel free to read through the source code to learn more.

Have you been experiencing issues with spam?

Best regards,

Michael

**Comment by michael-milette** [comment]
As there have been no additional communications in over a year, I will be closing this issue.

Best regards,

Michael
