### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by nestking18** [michael-milette/moodle-local_contact#61]
Hi,
 I installed the plugin, but I can't get to the email configuration to add the emails for a drop-down list with the emails for different subjects that i added with the HTML tags in a block. When I try to reconfigure the contact form plugin, my only option is to uninstall it. 
How can I fix the emails to contact each individual teacher?
Thanks.
Nestor

**Comment by michael-milette** [comment]
Hi @nestking18 ,

Did you follow the instructions found in the documentation? See
 https://github.com/michael-milette/moodle-local_contact/blob/master/README.md#optional-contact-form-for-moodle-settings

It describes what you need to do to set up exactly what you are trying to do.

Keep in mind that Contact form is a webmail form processor, not an HTML form editor. You still need to create the HTML form yourself. An example is also included in the documentation.

Let me know if you have any further questions.

Best regards,

Michael

**Comment by nestking18** [comment]
Thank you! Yes, I found the correction in the documentation, it's working.
