### ISSUE TITLE
Email only delivered for Admin users

### ISSUE THREAD

**Issue by michael-milette** [michael-milette/moodle-local_contact#62]
From Charles Duncan : I have implemented Contact Form in Moodle 3.9. It was easy to install and set up and is working well. The only problem is that emails are only being sent if the person using the form has administrator access to Moodle. For teachers, students, guests and non-logged-in users everything appears to work but the email never arrives. I am at a loss as to where to look and I suspect it may be related to some other setting outside Contact Form. Any suggestions?

**Comment by michael-milette** [comment]
I just ran some tests and determined that emails are sent regardless of whether the user is logged-in or not. I will continue to investigate. Please post a message here if this is also affecting your site.

**Comment by michael-milette** [comment]
I recently experienced the same issue with the Multi-Factor Authentication plugin. Emails were delivered correctly for admin accounts but not for teacher account. It might be a related issue. One possibility is that some emails are being caught by a SPAM filter at the client end.

**Comment by tasneemjahan** [comment]
Hi Michael,

I implemented this plugin on my moodle homepage (frontpage.mustache). However, I am only able to send emails when I am logged in as an admin or as a student.

When I am not logged in, it gives me an error:

![not-logged-in-error](https://user-images.githubusercontent.com/35711331/128283974-e39b0cc6-df50-406f-8f37-e395b23df077.JPG)
"A required parameter (email) was missing"

**Comment by michael-milette** [comment]
Hi @tasneemjahan ,

Please post your HTML form or a link to your home page.

Best regards, 

Michael

**Comment by tasneemjahan** [comment]
Hi @michael-milette 

Thanks for your quick reply. It actually worked for me now. Anyhow, this is my HTML form:
While you are here, can you please elaborate more on the security issues of this plugin: how spam emails are being handled by this plugin? Is there any step that we have to take to prevent spam?


                    <form action="local/contact/index.php" method="post" class="contact-us">
                        <fieldset>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="help"><p class="mb-md-3 mb-0">How can we help you? <strong class="required">*</strong></p></label>
                                </div>
                                <div class="col-md-8">
                                    <select class="contact-select form-select" name="How can we help you?" id="help" required="required">
                                        <option class="contact-option" value="" selected="">Please choose one</option>
                                        <option class="contact-option" id="login" value="I am not able to login">I am not able to login</option>
                                        <option class="contact-option" id="course" value="I am having trouble accessing or finding a resource">I am having trouble accessing or finding a resource</option>
                                        <option class="contact-option" id="account" value="I have issues with my account">I have issues with my account</option>
                                        <option class="contact-option" id="certificate" value="I am not able to access my course certificate">I am not able to access my course certificate</option>
                                        <option class="contact-option" id="wg" value="I am interested in getting involved with resource development">I am interested in getting involved with resource development</option>
                                        <option class="contact-option" id="new-resource" value="I would like to suggest a topic for a new resource">I would like to suggest a topic for a new resource</option>
                                        <option class="contact-option" id="others" value="Others">Other</option> 
                                        <optgroup></optgroup>     
                                    </select>
                                    <textarea rows="4" cols="50" id="editOption message" name="Details" minlength="5"  value="" style="display:none;" class="contact-textarea mt-3 mb-3" placeholder="Put the resource name or other details here"></textarea>
                                </div>          
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="name" id="namelabel"><p class="mb-md-3 mb-0  mt-md-0 mt-3">Name <strong class="required">*</strong></p></label>
                                </div>
                                <div class="col-md-8">
                                    <input class="contact-input" id="name" name="name" type="text" size="57" maxlength="45" pattern="[A-zÀ-ž]([A-zÀ-ž\s]){2,}" title="Minimum 3 letters/spaces." required="required" value="" placeholder="David John">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="min"><p class="mb-md-3 mb-0  mt-md-0 mt-3">MIN (if applicable)</p></label>
                                </div>
                                <div class="col-md-8">
                                    <input class="contact-input" type="text" id="min" name="MIN (if any)" value="" placeholder="123456">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="email" id="emaillabel"><p class="mb-md-3 mb-0  mt-md-0 mt-3">Email <strong class="required">*</strong></p></label>
                                </div>
                                <div class="col-md-8">
                                    <input class="contact-input" type="email" id="email" name="email" value="" placeholder="david.john@gmail.com">
                                </div>
                            </div>
                            <div class="row">
                                <div class="offset-md-4 col-md-5">
                                    <input type="submit" name="submit" id="submit" value="Send" class="btn btn-primary mt-md-0 mt-3 contact-submit-btn ml-0">
                                </div>
                                <div class="col-md-3">
                                    <input type="reset" value="Reset" class="btn btn-default mt-md-0 mt-3 contact-reset-btn ml-0" id="reset">
                                </div>  
                            </div>
                            <input type="hidden" id="sesskey" name="sesskey" value="">
                            <script>document.getElementById('sesskey').value = M.cfg.sesskey;</script>
                        </fieldset>  
                    </form>

**Comment by michael-milette** [comment]
Hi @tasneemjahan 

First, do not include your email address in the form. SPAM scrapers will pick it up and use it.

Are you actually getting spam email coming from the form or just want to know what spam prevention techniques are in place?

Michael

**Comment by tasneemjahan** [comment]
HI @michael-milette 

I just wanted to know what techniques are in place and if I need to do anything from my side. :)

**Comment by michael-milette** [comment]
There are several techniques in place to prevent spam. I have personally never received spam though my Moodle site using this plugin but that doesn't mean it is impossible. In addotion, you can activate reCAPTCHA if you find that you are getting spam.

Hopefully Moodle will upgrade its reCAPTCHA to v3 soon so that we can all turn on this anti-spam protection without requiring inconvenient manual intervention by users. When that  happens, I will of course hopefully be able to support it in Contact.

Best regards,

Michael

**Comment by tasneemjahan** [comment]
Thanks @michael-milette  for the information. Much appreciated.
I will let you know if I face any issues with the plugin.

Regards,
Tasneem

**Comment by michael-milette** [comment]
You are welcome @tasneemjahan ,

Please feel free to re-open this ticket if you are still having issues getting it to work.

Best regards,

Michael

**Comment by katsants** [comment]
Hey, Michel! Thanks for sharing your pluggin with us. I installed it and it's already configured in my Moodle, but I coudn't find where the form is placed on the main page to start sending some test emails.
