### ISSUE TITLE
contact us log

### ISSUE THREAD

**Issue by ainnab** [michael-milette/moodle-local_contact#64]
hi , is possible to see database log for the contact us page?

**Comment by michael-milette** [comment]
Hi @ainnab ,

There are no related logs in Moodle for emails sent using the Contact plugin. However, perhaps your email server might have logs. This plugin simply takes the content from the HTML form and sends it to your email server. It does not store any information.

If you would like to see this feature in a future version of Contact, please feel free to re-open this ticket and make it a feature request. If you need this feature integrated sooner than later, please contact me though my website at https://www.tngconsulting.ca/contact to make arrangements to sponsor higher priority development.

Best regards,

Michael
