### ISSUE TITLE
Validation error with multi-select field

### ISSUE THREAD

**Issue by dgmstudios** [michael-milette/moodle-local_contact#66]
Hello, first I want to thank you for your contribution with this fantastic plugin. The problem that I have detected occurs when we have a multiple select element in the form.

In your documentation, it is well reflected that the name of this field must end with [].

But, no matter how many times I tested, I could not get the information of this field to appear in mails.

Reviewing the code, in the function "sendmessage", when it begins to process the collected information, there is a conditional:

`if (!in_array($key, array('sesskey', 'submit')) && trim($value) != '') {`

The parameter provided to trim should be a string. But when a multi-select field is used in the form then it is an array.

`PHP Warning:  trim() expects parameter 1 to be string, array given in /sites/yoursite/files/local/contact/classes/local_contact.php on line 268`

A solution could be to move this part of the code, before excluding the empty information fields.

`// Join array of values. Example: <select multiple>.
if (is_array($value)) {
$value = join(', ', $value);
}`

**Comment by michael-milette** [comment]
Hi @dgmstudios ,

Thank you for taking the time to report this issue. I was able to reproduce it successfully. The issue has been resolved and is now available for download. Please let me know if it works for you.

Best regards,

Michael Milette

**Comment by dgmstudios** [comment]
It works properly. Thanks for the update

Best regards.
