### ISSUE TITLE
Bug: {formcontactus} formatting error

### ISSUE THREAD

**Issue by RogueAgent991** [michael-milette/moodle-local_contact#72]
### Prerequisites

- [X] I'm reporting the issue to the correct repository.
- [X] I am running the latest version of this plugin (if not, please upgrade first).
- [X] I checked the [README.md](../blob/master/README.md) and [Wiki](../wiki) documentation but did not find my answer.
- [X] I searched to make sure that this issue had not already been reported.
- [X] I have, or I know someone who has, the ability and willingness to test the fix on a Moodle LMS-based site.
- [X] I am submitting no more than one bug report per issue ticket (please do not submit multiple bugs in one issue ticket).
- [X] I understand that support is provided by volunteer(s).

### What happened?

I am using {formcontactus}.
The form created has massive spaces and is not well formatted in general.
I am using Cognitio theme.

![temp - Contact us](https://github.com/michael-milette/moodle-local_contact/assets/71994397/3f688606-a3b6-4fa1-bfae-21afc55632cd)

### What do you think should have happened?

I expected a better formatted form. 

### Steps to reproduce

1. Go to https://sppic.ca
2. Scroll to the bottom.
3. Click on Contact us (in blue, haven't fixed that yet).
4. See error or issue.

### Screenshots

![temp - Contact us 1](https://github.com/michael-milette/moodle-local_contact/assets/71994397/af633700-25f9-4719-a6a2-adeb3c6cc306)
![temp - Contact us 2](https://github.com/michael-milette/moodle-local_contact/assets/71994397/01a1884f-4b35-470b-ae17-d7c029e44914)

### Moodle version

4.1.1

### Installed Moodle UI Language packs.

- [X] English only
- [ ] One or more other languages/regional dialects (specify below)
- [ ] Other

### System information

Client Device type: (e.g. Desktop, iPhone or iPad, Android phone or tablet, Other - specify)
Client Operating System: (e.g. Windows, Linux, Mac OS, Android, iOS, Other - specify)
Client Web Browser: (e.g. Chrome, Edge, Firefox, Safari, Safe Exam Browser, Moodle Mobile App)
Server Operating System: (e.g. Windows, Linux, Mac OS, Other - specify)
Server Webserver: (e.g. Apache, Nginx, IIS, Other - specify)
Server PHP: (e.g. 7.3, 7.4, 8.x, Other - specify)

### Code of Conduct

- [X] I have read and agree to the project's <a href="../blob/master/CODE_OF_CONDUCT.md" target="_blank">code of conduct</a>.

**Comment by michael-milette** [comment]
Hi @RogueAgent991 ,

The issue you are experiencing is related to the CSS of your theme. To fix the problem, you will need to customize the CSS for the form.

You can see this by temporarily switching to the Boost theme.

If you would like some help with this, please feel free to contact me at https://tngconsulting.ca/contact for premium support.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @RogueAgent991 ,

I took a quick look at your form online. Seems that you have an HTML "pre" and a "code" tag around the filtercodes tag. Remove those from the HTML view in the Moodle editor and you will find that it all looks great.

<img width="400" alt="image" src="https://github.com/michael-milette/moodle-local_contact/assets/3808579/4daf2fe1-a3ea-4ddb-b52c-271ea66cbdba">

Best regards,

Michael
